import type { Metadata } from "next";
import { LegalDoc, COMPANY, type LegalSection } from "@/components/site/LegalDoc";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms that govern your use of BitapTech's website, products, and WhatsApp Business messaging platform.",
  robots: { index: true, follow: true },
  alternates: { canonical: "/terms" },
};

const LAST_UPDATED = "14 July 2026";

const sections: LegalSection[] = [
  {
    heading: "Electronic record and Platform Owner",
    body: [
      "This document is an electronic record in terms of the Information Technology Act, 2000 and the rules thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.",
      "This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the domain name www.bitaptech.com (the \"Website\"), including the related mobile site and mobile application (the \"Platform\").",
      `The Platform is owned by 6351910962, a company incorporated under the Companies Act, 1956, with its registered office at rongpara,andichak,chitrasenpur (the "Platform Owner", "we", "us", "our"). ${COMPANY.name} is the brand under which the Platform Owner operates.`,
    ],
  },
  {
    heading: "Acceptance of terms",
    body: [
      `By accessing or using ${COMPANY.name}'s website, dashboards, APIs, and products (together, the "Services"), you agree to be bound by these Terms of Service. If you use the Services on behalf of a business, you represent that you are authorised to bind that business.`,
      "Accessing, browsing or otherwise using the Platform indicates your agreement to all the terms and conditions under these Terms of Use, so please read the Terms of Use carefully before proceeding. If you transact on the Platform, you shall be subject to the policies that are applicable to the Platform for such transaction. Any terms and conditions proposed by you which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time, and it is your responsibility to periodically review them to stay informed of updates.",
    ],
  },
  {
    heading: "General terms of use",
    body: [
      "The use of the Platform and/or availing of our Services is subject to the following terms:",
      {
        list: [
          "You agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.",
          "Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this Website or through the Services for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.",
          "Your use of our Services and the Platform is solely and entirely at your own risk and discretion, for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.",
          "The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents, which include but are not limited to the design, layout, look and graphics.",
          "You acknowledge that unauthorised use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.",
          "You agree to pay us the charges associated with availing the Services, and you agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or by Indian or local laws that might apply to you.",
          "The Website and the Services may contain links to third-party websites. On accessing these links, you will be governed by the terms of use, privacy policy and other policies of such third-party websites. These links are provided for your convenience to provide further information.",
          "You understand that upon initiating a transaction for availing the Services, you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.",
        ],
      },
    ],
  },
  {
    heading: "The Services",
    body: [
      `${COMPANY.name} provides software products including ${COMPANY.product}, a WhatsApp Business messaging platform built on Meta's official WhatsApp Cloud API. Features may include connecting a WhatsApp Business Account, sending template campaigns, automating conversations with AI, and managing contacts. We may add, change, or remove features over time.`,
    ],
  },
  {
    heading: "Product-specific terms",
    body: [
      `${COMPANY.name} offers more than one WhatsApp product, and some terms depend on which product you use:`,
      "WpAi Official (Meta WhatsApp Cloud API): Built on Meta's official WhatsApp Cloud API. Your use is subject to the WhatsApp and Meta compliance obligations set out below, and messaging is billed on the prepaid wallet model described in these terms.",
      `WpAi Unofficial (device-based sync): An independent software tool that connects to your own WhatsApp session (based on WPPConnect/Baileys web clients). It is not affiliated with, endorsed by, or officially connected to Meta Platforms, Inc. or WhatsApp, and the use of automated client scripts may violate Meta's WhatsApp Terms of Service. You assume sole responsibility for your connected numbers, and ${COMPANY.name} is not liable for rate limiting, message blocking, or temporary or permanent suspensions or bans imposed by Meta or network carriers. We recommend using secondary numbers for cold outbound messaging and conservative rate throttling. This product is billed on a subscription basis (including any free trial) rather than the prepaid wallet model.`,
    ],
  },
  {
    heading: "Eligibility and accounts",
    body: [
      "You must be at least 18 years old and able to form a binding contract to use the Services. You are responsible for the accuracy of your account information, for keeping your credentials secure, and for all activity that occurs under your account.",
    ],
  },
  {
    heading: "WhatsApp and Meta compliance",
    body: [
      "When you use our WhatsApp Business messaging features, you agree to comply with all applicable Meta and WhatsApp policies, including the WhatsApp Business Messaging Policy, WhatsApp Commerce Policy, and Meta's Business Terms.",
      {
        list: [
          "You must obtain valid opt-in consent from recipients before messaging them.",
          "You must not send spam, unsolicited, deceptive, or prohibited content.",
          "You are responsible for the content of the messages and templates you send.",
          "Meta may review, restrict, or disable message templates, phone numbers, or accounts at its discretion, and we are not liable for such actions.",
        ],
      },
    ],
  },
  {
    heading: "Acceptable use",
    body: [
      "You agree not to:",
      {
        list: [
          "Use the Services for any unlawful, harmful, fraudulent, or abusive purpose.",
          "Send messages without proper consent or in violation of applicable laws (including anti-spam and data protection laws).",
          "Attempt to disrupt, reverse engineer, scrape, or gain unauthorised access to the Services.",
          "Resell or provide access to the Services in a way that violates these terms or Meta's policies.",
        ],
      },
    ],
  },
  {
    heading: "Wallet, billing, and pricing",
    body: [
      "The Services operate on a prepaid wallet model. You recharge your wallet, and message charges are metered per message based on Meta's conversation rates and the destination country and category. Applicable taxes (such as GST) are added where required.",
      "Prices and Meta's underlying rates may change. We will make current pricing available in the dashboard. Wallet balances and message charges are governed by our Refund Policy.",
    ],
  },
  {
    heading: "Third-party services",
    body: [
      "The Services rely on third parties including Meta (WhatsApp Cloud API), payment processors (such as Razorpay, Stripe, and PhonePe), and AI providers (such as Groq, OpenAI, and Anthropic). Your use of those features is also subject to the respective third party's terms. We are not responsible for the availability, acts, or omissions of third-party services.",
    ],
  },
  {
    heading: "Service availability",
    body: [
      'We work to keep the Services reliable but do not guarantee uninterrupted or error-free operation. The Services are provided "as is" and "as available", without warranties of any kind, whether express or implied, to the maximum extent permitted by law.',
    ],
  },
  {
    heading: "Intellectual property",
    body: [
      `All software, content, product names, logos, and code that make up the Services are the property of ${COMPANY.name} or its licensors, unless otherwise stated. You retain ownership of the content and data you upload; you grant us a limited licence to process it solely to provide the Services.`,
    ],
  },
  {
    heading: "Limitation of liability",
    body: [
      `To the maximum extent permitted by law, ${COMPANY.name} shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or for loss of profits, data, or business, arising out of or related to your use of the Services. Our total liability for any claim shall not exceed the amounts you paid to us for the Services in the three months preceding the claim.`,
    ],
  },
  {
    heading: "Indemnity",
    body: [
      `You agree to indemnify and hold ${COMPANY.name} harmless from any claims, damages, or expenses arising from your use of the Services, your content or messages, or your violation of these terms or applicable law (including Meta's and WhatsApp's policies).`,
    ],
  },
  {
    heading: "Suspension and termination",
    body: [
      "We may suspend or terminate your access to the Services if you breach these terms, violate Meta's or WhatsApp's policies, or use the Services in a way that creates risk or legal exposure. You may stop using the Services at any time. Certain provisions (such as intellectual property, limitation of liability, and indemnity) survive termination.",
    ],
  },
  {
    heading: "Changes to these terms",
    body: [
      'We may update these terms from time to time. Changes take effect when posted, and we will update the "Last updated" date above. Your continued use of the Services after changes take effect constitutes acceptance.',
    ],
  },
  {
    heading: "Force majeure",
    body: [
      "Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.",
    ],
  },
  {
    heading: "Governing law",
    body: [
      `These terms and any dispute or claim relating to them, or their enforceability, are governed by and construed in accordance with the laws of ${COMPANY.jurisdiction}. The courts located in ${COMPANY.jurisdiction} shall have exclusive jurisdiction over any disputes, unless otherwise required by applicable law. All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this Website.`,
    ],
  },
];

export default function TermsPage() {
  return (
    <LegalDoc
      title="Terms of Service"
      lastUpdated={LAST_UPDATED}
      intro={`These terms govern your use of ${COMPANY.name}'s website, products, and WhatsApp Business messaging platform. Please read them carefully.`}
      sections={sections}
    />
  );
}
